//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreadSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleCompra
    {
        public int idDetalleCompra { get; set; }
        public int idMateriaP { get; set; }
        public int idCompra { get; set; }
        public int cantidad { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual materiaPrima materiaPrima { get; set; }
    }
}
